sudo: false
language: generic
cache:
  timeout: 360
  directories:
  - "$HOME/.stack/"
  - "$HOME/.local/bin/"
  - ".stack-work/"
install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
jobs:
  include:
    - stage: install cabal
      script: stack --no-terminal build -j 1 Cabal
    - stage: install pandoc
      script: stack --no-terminal build pandoc
    - stage: install deprndences
      script: stack --no-terminal test --only-dependencies
    - stage: stack test
      script: stack --no-terminal test
    - stage: rebuild site
      script: stack exec site rebuild
    - stage: deploy
      if: branch = site-auto-publish AND type IN (push)
      script: stack exec site rebuild
      after_success:
      - eval "$(ssh-agent -s)"
      - chmod 600 deploy_key
      - ssh-add deploy_key
      - cp  -r _site/ site/
      - git add site/*
      - git status
      - git checkout site
      - git commit -m "by Travis CI (JOB $TRAVIS_JOB_NUMBER)"
      - git push origin :site
before_install:
- openssl aes-256-cbc -K $encrypted_c401a9e03794_key -iv $encrypted_c401a9e03794_iv
  -in deploy_key.enc -out deploy_key -d
