sudo: false
language: generic
branches:
  only:
  - site-auto-publish
cache:
  directories:
  - "$HOME/.stack/"
  - "$HOME/.local/bin/"
  - ".stack-work/"
before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
install:
- stack --no-terminal build -j 1 Cabal
- stack --no-terminal test --only-dependencies
jobs:
  include:
    - stage: stack test
      script: stack --no-terminal test
    - stage: site build test
      script: stack exec site rebuild
    - stage: deploy
      if: type IN (push)
      script: echo "deploy!!"
      # comment by pull-request-branch